import tempfile
import os
import base64
import subprocess
import shutil
from pathlib import Path


def convert_pptx_to_images(pptx_path: str, scale: int = 2) -> list[str]:
    """
    convert PPTX slides to base64-encoded PNG images using LibreOffice
    returns list of base64 strings (one per slide)
    """
    # validate input path to prevent command injection
    if not os.path.exists(pptx_path):
        raise ValueError(f'file does not exist: {pptx_path}')
    
    # ensure path is absolute and normalized
    pptx_path = os.path.abspath(pptx_path)
    
    # validate file extension
    if not pptx_path.endswith('.pptx'):
        raise ValueError('file must have .pptx extension')
    # find libreoffice executable
    libreoffice_paths = [
        '/Applications/LibreOffice.app/Contents/MacOS/soffice',  # macos
        'libreoffice',  # linux
        'soffice',  # alternative
        '/usr/bin/libreoffice',
        '/usr/local/bin/libreoffice',
    ]
    
    libreoffice_cmd = None
    for path in libreoffice_paths:
        if shutil.which(path) or os.path.exists(path):
            libreoffice_cmd = path
            break
    
    if not libreoffice_cmd:
        raise RuntimeError(
            "LibreOffice not found. Please install LibreOffice to generate slide previews. "
            "Visit https://www.libreoffice.org/download/download/"
        )
    
    with tempfile.TemporaryDirectory() as tmpdir:
        try:
            # convert PPTX to PDF using LibreOffice
            pdf_output_dir = os.path.join(tmpdir, 'pdf')
            os.makedirs(pdf_output_dir, exist_ok=True)
            
            # run libreoffice headless conversion
            cmd = [
                libreoffice_cmd,
                '--headless',
                '--convert-to', 'pdf',
                '--outdir', pdf_output_dir,
                pptx_path
            ]
            
            result = subprocess.run(
                cmd,
                stdout=subprocess.PIPE,
                stderr=subprocess.PIPE,
                timeout=60,
                text=True
            )
            
            if result.returncode != 0:
                raise RuntimeError(f"LibreOffice conversion failed: {result.stderr}")
            
            # find the generated PDF
            pdf_files = list(Path(pdf_output_dir).glob('*.pdf'))
            if not pdf_files:
                raise RuntimeError("No PDF generated by LibreOffice")
            
            pdf_path = str(pdf_files[0])
            
            # convert PDF to images using sips (macOS) or imagemagick (linux)
            images = []
            
            # try using sips (macOS native tool)
            if shutil.which('sips'):
                images = _convert_pdf_with_sips(pdf_path, tmpdir, scale)
            # try using imagemagick/magick
            elif shutil.which('convert') or shutil.which('magick'):
                images = _convert_pdf_with_imagemagick(pdf_path, tmpdir, scale)
            else:
                # fallback: return empty list (will use placeholder preview)
                print("warning: no image conversion tool found (sips or imagemagick)")
                return []
            
            return images
            
        except subprocess.TimeoutExpired:
            raise RuntimeError("LibreOffice conversion timed out after 60 seconds")
        except Exception as e:
            print(f"error converting PPTX to images: {e}")
            raise


def _convert_pdf_with_sips(pdf_path: str, tmpdir: str, scale: int) -> list[str]:
    """convert PDF to PNG using macOS sips tool"""
    # validate paths to prevent injection
    pdf_path = os.path.abspath(pdf_path)
    tmpdir = os.path.abspath(tmpdir)
    
    # note: sips doesn't support multi-page PDFs directly
    # we need to first split the PDF or use a different approach
    # for now, just convert first page
    png_dir = os.path.join(tmpdir, 'png')
    os.makedirs(png_dir, exist_ok=True)
    
    # use pdftoppm if available (comes with poppler)
    if shutil.which('pdftoppm'):
        return _convert_pdf_with_pdftoppm(pdf_path, tmpdir, scale)
    
    # fallback to single page with sips
    output_path = os.path.join(png_dir, 'slide_0.png')
    cmd = [
        'sips',
        '-s', 'format', 'png',
        '--out', output_path,
        pdf_path
    ]
    subprocess.run(cmd, check=True, capture_output=True, timeout=30)
    
    return _encode_images_from_dir(png_dir)


def _convert_pdf_with_imagemagick(pdf_path: str, tmpdir: str, scale: int) -> list[str]:
    """convert PDF to PNG using ImageMagick"""
    # validate paths to prevent injection
    pdf_path = os.path.abspath(pdf_path)
    tmpdir = os.path.abspath(tmpdir)
    
    png_dir = os.path.join(tmpdir, 'png')
    os.makedirs(png_dir, exist_ok=True)
    
    output_pattern = os.path.join(png_dir, 'slide.png')
    
    # density controls quality (72 = screen, 150 = good, 300 = high)
    density = 72 * scale
    
    cmd = [
        'convert' if shutil.which('convert') else 'magick',
        '-density', str(density),
        pdf_path,
        '-quality', '90',
        output_pattern
    ]
    
    subprocess.run(cmd, check=True, capture_output=True, timeout=60)
    
    return _encode_images_from_dir(png_dir)


def _convert_pdf_with_pdftoppm(pdf_path: str, tmpdir: str, scale: int) -> list[str]:
    """convert PDF to PNG using pdftoppm (poppler-utils)"""
    # validate paths to prevent injection
    pdf_path = os.path.abspath(pdf_path)
    tmpdir = os.path.abspath(tmpdir)
    
    png_dir = os.path.join(tmpdir, 'png')
    os.makedirs(png_dir, exist_ok=True)
    
    output_prefix = os.path.join(png_dir, 'slide')
    
    # scale controls resolution (1 = 150dpi, 2 = 300dpi)
    resolution = 150 * scale
    
    cmd = [
        'pdftoppm',
        '-png',
        '-r', str(resolution),
        pdf_path,
        output_prefix
    ]
    
    subprocess.run(cmd, check=True, capture_output=True, timeout=60)
    
    return _encode_images_from_dir(png_dir)


def _encode_images_from_dir(png_dir: str) -> list[str]:
    """encode all PNG files in directory to base64 data URLs"""
    images = []
    png_files = sorted(Path(png_dir).glob('*.png'))
    
    for png_file in png_files:
        with open(png_file, 'rb') as f:
            img_data = base64.b64encode(f.read()).decode('utf-8')
            images.append(f"data:image/png;base64,{img_data}")
    
    return images
